POST http://127.0.0.1:8000/account/register/
Content-Type: application/json

{
  "username": "tinashe",
  "email": "tinashe@example.com",
  "password": "StrongPass123"
}

###

POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "tinashe",
  "password": "StrongPass123"
}